name: CI Build

on:
  workflow_dispatch:
    inputs:
        version_name:
          required: true
          description: Nhập version name (ví dụ 1.0.0)
          default: 1.0.0 # To trigger manual build
        version_code:
          required: true
          description: Nhập version code (ví dụ 1)
          default: 1 # To trigger manual build
  release:
    types: [published] # only run the workflow when a new release has been published

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
      - run: flutter clean
      - run: |
          cd packages/jesus && touch .env && echo APP_NAME=UboxDev > .env &&
          echo API_URL=API_URL=https://heracles.gobizdev.com/api >> .env &&
          echo API_LOGIN_URL="https://heracles.gobizdev.com/login"  >> .env && 
          echo API_LOGOUT_URL=https://heracles.gobizdev.com/confirm_logout  >> .env &&
          echo ANDROID_APP_ID=com.ordermanagement  >> .env &&
          echo ANDROID_APP_VERSION_NAME=${{ github.event.inputs.version_name }}  >> .env &&
          echo ANDROID_APP_VERSION_CODE=${{ github.event.inputs.version_code }}  >> .env && 
          cat .env && ls
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: |
          cd packages/jesus && touch .env && echo APP_NAME=UboxDev > .env &&
          echo API_URL=API_URL=https://heracles.gobizdev.com/api >> .env &&
          echo API_LOGIN_URL="https://heracles.gobizdev.com/login"  >> .env && 
          echo API_LOGOUT_URL=https://heracles.gobizdev.com/confirm_logout  >> .env &&
          echo ANDROID_APP_ID=com.ordermanagement  >> .env &&
          echo ANDROID_APP_VERSION_NAME=${{ github.event.inputs.version_name }}  >> .env &&
          echo ANDROID_APP_VERSION_CODE=${{ github.event.inputs.version_code }}  >> .env && 
          cat .env && ls
      - run: flutter build apk --flavor dev
      - run: flutter build appbundle --flavor dev