name: CI Build
on:
  workflow_dispatch:
    inputs:
        version_name:
          required: true
          description: Nhập version name (ví dụ 1.0.0)
          default: 1.0.0 # To trigger manual build
        version_code:
          required: true
          description: Nhập version code (ví dụ 1)
          default: 1 # To trigger manual build
          
jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.3.8'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle